---
- hosts: mysqlserver
  tasks:
    - name: Create SSH key for user
      user:
        name: root
        generate_ssh_key: yes
        ssh_key_file: /root/.ssh/id_rsa

- hosts: mysqlbackupserver
  tasks: 
    - name: test
      authorized_key: 
         user: root
         state: present
         manage_dir: yes
         key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
