---
# tasks file for mysql-configure

- name: Create .my.cnf file
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0775


# When MySql is installed, root user is left with no password
# In this step, we set password for the root user
# We will set the password using ansible vault
- name: Set root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
  with_items:
    - "{{ ansible_hostname }}"
  ignore_errors: true

- debug:
    msg: "{{ ansible_hostname }}"

# Removing the default user since it will not be used
- name: Delete default user
  mysql_user:
    name: ""
    state: absent
  ignore_errors: true


# Removing test database since it will not be used
- name: Remove test database
  mysql_db:
    name: test
    state: absent
  ignore_errors: true
